version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/applicat
  
  - source: /applicat.wsgi
    destination: /var/www/applicat
  
  - source: /conf/applicat.conf
    destination: /etc/apache2/sites-available

hooks:
  AfterInstall:
    - location: scripts/install_dependancy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root    


